services:
  # Base de datos Oracle Express
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    container_name: factumarket-oracle
    environment:
      - ORACLE_PWD=Oracle123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"  # Oracle Enterprise Manager Express
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./oracle-init:/opt/oracle/scripts/startup
    networks:
      - factumarket-network
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/Oracle123@//localhost:1521/XE", "@/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Servicio de clientes
  clientes-service:
    build:
      context: ./backend/clientes-service
      dockerfile: Dockerfile.simple
    container_name: factumarket-clientes-service
    environment:
      - RAILS_ENV=development
      - ORACLE_HOST=oracle-db
      - ORACLE_PORT=1521
      - ORACLE_SERVICE_NAME=XEPDB1
      - ORACLE_USERNAME=clientes_service
      - ORACLE_PASSWORD=clientes123
      - RAILS_MAX_THREADS=5
    ports:
      - "3000:3000"
    volumes:
      - ./backend/clientes-service:/app
      - clientes_logs:/app/log
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - factumarket-network
    restart: unless-stopped

volumes:
  oracle_data:
    driver: local
  clientes_logs:
    driver: local

networks:
  factumarket-network:
    driver: bridge