-- Script para crear el usuario de la aplicación clientes-service
-- Este script se ejecuta automáticamente cuando Oracle se inicia

-- Conectar a la PDB
ALTER SESSION SET CONTAINER = XEPDB1;

-- Crear usuario para el servicio de clientes
CREATE USER clientes_service IDENTIFIED BY clientes123;

-- Otorgar privilegios necesarios
GRANT CONNECT, RESOURCE TO clientes_service;
GRANT CREATE SESSION TO clientes_service;
GRANT CREATE TABLE TO clientes_service;
GRANT CREATE SEQUENCE TO clientes_service;
GRANT CREATE VIEW TO clientes_service;
GRANT CREATE PROCEDURE TO clientes_service;
GRANT CREATE TRIGGER TO clientes_service;

-- Otorgar privilegios adicionales para desarrollo
GRANT UNLIMITED TABLESPACE TO clientes_service;

-- Crear algunas tablas de ejemplo para el servicio de clientes
-- (Esto se puede modificar según las necesidades específicas)

-- Tabla de clientes
CREATE TABLE clientes_service.clientes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    identificacion VARCHAR2(20) NOT NULL UNIQUE,
    email VARCHAR2(100),
    direccion VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Insertar algunos clientes de ejemplo
INSERT INTO clientes_service.clientes (nombre, identificacion, email, direccion) VALUES 
('Juan Pérez', '12345678', 'juan.perez@email.com', 'Calle Principal 123');
INSERT INTO clientes_service.clientes (nombre, identificacion, email, direccion) VALUES 
('María García', '87654321', 'maria.garcia@email.com', 'Avenida Central 456');
INSERT INTO clientes_service.clientes (nombre, identificacion, email, direccion) VALUES 
('Carlos López', '11223344', 'carlos.lopez@email.com', 'Plaza Mayor 789');

COMMIT;

-- Mostrar información de confirmación
SELECT 'Usuario clientes_service creado exitosamente' AS mensaje FROM DUAL;
SELECT COUNT(*) AS total_clientes FROM clientes_service.clientes;