-- Script para crear el usuario de la aplicación clientes-service
-- Este script se ejecuta automáticamente cuando Oracle se inicia

-- Crear usuario para el servicio de clientes
CREATE USER clientes_service IDENTIFIED BY clientes123;

-- Otorgar privilegios necesarios
GRANT CONNECT, RESOURCE TO clientes_service;
GRANT CREATE SESSION TO clientes_service;
GRANT CREATE TABLE TO clientes_service;
GRANT CREATE SEQUENCE TO clientes_service;
GRANT CREATE VIEW TO clientes_service;
GRANT CREATE PROCEDURE TO clientes_service;
GRANT CREATE TRIGGER TO clientes_service;

-- Otorgar privilegios adicionales para desarrollo
GRANT UNLIMITED TABLESPACE TO clientes_service;

-- Crear algunas tablas de ejemplo para el servicio de clientes
-- (Esto se puede modificar según las necesidades específicas)

-- Tabla de clientes
CREATE TABLE clientes_service.clientes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE,
    telefono VARCHAR2(20),
    direccion VARCHAR2(255),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de categorías de clientes
CREATE TABLE clientes_service.categorias_cliente (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    descripcion VARCHAR2(255),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insertar datos de ejemplo
INSERT INTO clientes_service.categorias_cliente (nombre, descripcion) VALUES ('VIP', 'Clientes VIP con descuentos especiales');
INSERT INTO clientes_service.categorias_cliente (nombre, descripcion) VALUES ('Regular', 'Clientes regulares');
INSERT INTO clientes_service.categorias_cliente (nombre, descripcion) VALUES ('Nuevo', 'Clientes nuevos');

-- Insertar algunos clientes de ejemplo
INSERT INTO clientes_service.clientes (nombre, identificacion, email, direccion) VALUES 
('Juan Pérez', '12345678', 'juan.perez@email.com', 'Calle Principal 123');
INSERT INTO clientes_service.clientes (nombre, identificacion, email, direccion) VALUES 
('María García', '87654321', 'maria.garcia@email.com', 'Avenida Central 456');
INSERT INTO clientes_service.clientes (nombre, identificacion, email, direccion) VALUES 
('Carlos López', '11223344', 'carlos.lopez@email.com', 'Plaza Mayor 789');

COMMIT;

-- Mostrar información de confirmación
SELECT 'Usuario clientes_service creado exitosamente' AS mensaje FROM DUAL;
SELECT COUNT(*) AS total_clientes FROM clientes_service.clientes;
SELECT COUNT(*) AS total_categorias FROM clientes_service.categorias_cliente;